config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'forums#index'
  resources :users, only: [:index, :edit, :update]
  resources :forums, only: [:index, :new, :create, :edit, :update] do
    resources :posts, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum.rb
class Forum < ApplicationRecord
  has_many :forum_users
  has_many :users, through: :forum_users
  has_many :posts
  validates :name, presence: true, uniqueness: true

  def show_last_post
    if (last_post = posts.last).present?
      if last_post.text?
        last_post.text
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/forum_user.rb
class ForumUser < ApplicationRecord
  belongs_to :forum
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :forum
  belongs_to :user

  mount_uploader :image, ImageUploader
  validates :text, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :forum_users
  has_many :forums, through: :forum_users
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

  def index
  end

  def new
    @forum = Forum.new
    @forum.users << current_user
    @members = @forum.users
  end

  def create
    @forum = Forum.new(forum_params)
    if @forum.save
      redirect_to root_path, notice: '企業チャットを作成しました'
    else
      render :new
    end
  end

  def edit
    @forum = Forum.find(params[:id])
  end

  def update
    @forum = Forum.find(params[:id])
    if @forum.update(forum_params)
      redirect_to root_path, notice: '企業チャットを更新しました'
    else
      render :edit
    end
  end

  private
  def forum_params
    params.require(:forum).permit(:name, user_ids: [])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_group

  def index
    @post = Post.new
    @posts = @forum.posts.includes(:user)
    @members = @forum.users
  end

  def create
    @post = @forum.posts.new(post_params)
    if @post.save
      redirect_to forum_posts_path(@forum), notice: 'メッセージが送信されました'
      # redirect_to group_messages_path(@group)
    else
      @posts = @forum.posts.includes(:user)
      # @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def post_params
    params.require(:post).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_group
    @forum = Forum.find(params[:forum_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forums/_form.html.haml
= form_for forum do |f|
  - if forum.errors.any?
    .chat-forum-form__errors
      %h2= "#{forum.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - forum.errors.full_messages.each do |message|
          %li= message
  .chat-forum-form__field
    .chat-forum-form__field--left
      = f.label :name, class: 'chat-forum-form__label'
    .chat-forum-form__field--right
      = f.text_field :name, class: 'chat__forum_name chat-forum-form__input', placeholder: 'グループ名を入力してください'
  .chat-forum-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-forum-form__field.clearfix
    .chat-forum-form__field--left
      %label.chat-forum-form__label{:for => "chat_forum_チャットメンバー"} チャットメンバー
    .chat-forum-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-forum-form__field.clearfix
    .chat-forum-form__field--left
    .chat-forum-form__field--right
      = f.submit class: 'chat-forum-form__action-btn'

app/views/forums/edit.html.haml
.chat-forum-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { forum: @forum }

app/views/forums/index.html.haml
.wrapper
  = render 'devise/shared/side_bar'

app/views/forums/new.html.haml
=form_for @forum do |f|
  = f.text_field :name, class: "chat-forum-form__input", placeholder: "企業名を入力してください"
  = f.collection_check_boxes :user_ids, User.all, :id, :name
  = f.submit "Save", class: "chat-forum-form__action-btn"

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Kabu-talk
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/posts/_main_chat.html.haml
.posts
  = render @posts

app/views/posts/_post.html.haml
.post
  .upper-post
    .upper-post__user-name
      = post.user.name
    .upper-post__date
      = post.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .lower-post
    - if post.text.present?
      %p.lower-post__content
        = post.text
    = image_tag post.image.url, class: 'lower-post__image' if post.image.present?

app/views/posts/index.html.haml
.flash-box
  .wrapper
    -# = render 'devise/shared/side_bar'
    .chat-main
      .main-header
        .main-header__left-box
          %h2.main-header__left-box__current-forum{ data: {forum: {id: params[:forum_id]}} } 
            = @forum.name
          %ul.main-header__left-box__member-list
            Member：
            - @members.each do |member|
              = member.name
        = link_to edit_forum_path(params[:forum_id]) do
          .main-header__edit-btn Edit
      .posts
        = render @posts
      .form
        = form_for [@forum, @post] do |f|
          = f.text_field :text, class: 'form__post', placeholder: '  コメントする'
          .form__mask
            = f.label :image, class: 'form__mask__image' do
              = fa_icon 'paperclip', class: 'icon'
              = f.file_field :image, class: 'hidden'
          = f.submit '投稿する', class: 'form__submit'

    = render 'devise/shared/side_bar'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'